### ISSUE TITLE
Hi, Do you use the official pytorch 0.4.0 version? I always meet the segmentation fault.

### ISSUE THREAD

**Issue by shanyuhu** [jiaxue1993/Deep-Encoding-Pooling-Network-DEP-#1]

**Comment by jiaxue-ai** [comment]
thanks for your feedback, I fix some bug of the code. I think the reason for your segmentation fault error might be incorrectly pytorch install. try the command **python -c  "import encoding"** in terminal to check whether the encoding layer is installed correctly. You need to install pytorch from source
